var Frame=function(a){this.index=a.index;this.eventContainerId=a.eventContainerId;this.tools=a.arr;this.titles=a.titles;this.n=a.imgNumber||4;this.imgSize=a.imgSize||56;this.rows=a.rowsNumber||1;this.positionY=a.shiftPx||-58;this.speed=a.speed||1E3;this.current=0;this.parnt=a.parnt||"parnt";this.firstSibling=a.firstSibling||"firstSibling";this.secondSibling=a.secondSibling||"secondSibling";this.content=a.content||"some content";this.image=a.image;this.timerFlag=!0;this.arrIsNull=function(){var e,
b=!0,c=a.arr.length,f=a.arr;for(e=0;e<c;e++)0!==f[e]&&(b=!1);return b}();this.toolsA=function(){var e,b=[],c=[],f=a.arr.length,h=a.arr,k=a.titles;for(e=0;e<f;e++)0<h[e]?(b.push(h[e]),k[e].level=h[e],k[e].tooltip=k[e].title+" "+rome_nums[h[e]],c.push(k[e])):delete k[e];return{tools:b,title:c}}();this.numOfFrames=Math.ceil(this.toolsA.tools.length/this.n);var c=document.getElementById(this.eventContainerId);"function"===typeof window.addEventListener?(c.addEventListener("click",function(a){return function(b){a.handler(b,
a)}}(this),!1),c.addEventListener("mouseover",function(a){return function(b){a.handler(b,a)}}(this),!1),c.addEventListener("mouseout",function(a){return function(b){a.handler(b,a)}}(this),!1)):(c.attachEvent("onclick",function(a){return function(b){a.handler(b,a)}}(this)),c.attachEvent("onmouseover",function(a){return function(b){a.handler(b,a)}}(this)),c.attachEvent("onmouseout",function(a){return function(b){a.handler(b,a)}}(this)))};
Frame.prototype.getElementsByClassName=function(a,c){if(document.getElementsByClassName)return document.getElementsByClassName(c);for(var e=[],b=new RegExp("(^| )"+c+"( |$)"),g=a.getElementsByTagName("*"),f=0,h=g.length;f<h;f++)b.test(g[f].className)&&e.push(g[f]);return e};
Frame.prototype.handler=function(a,c){a||(a=window.event);var e=a.target||a.srcElement,b=a.type;a.stopPropagation?a.stopPropagation():a.cancelBubble=!0;switch(b){case "click":b=e.nodeName.toLowerCase();if("div"===b&&!0===c.timerFlag)switch(e.id||e.className){case "forward":c.current!==c.numOfFrames-1&&(c.shiftR(),c.current++);c.timer();break;case "back":0!==c.current&&(c.shiftL(),c.current--),c.timer()}else break;break;case "mouseover":var b=e.nodeName.toLowerCase(),g=e.getAttribute("data-title");
if("img"!==b)break;else tooltip(e,g);break;case "mouseout":hide_info(e)}};Frame.prototype.containersCreator=function(a,c,e,b){b.name=b.name.split(" ");b.val=b.val.split(" ");a=document.getElementById(a);for(var g=0;g<e;g++){var f=document.createElement(c);f.setAttribute(b.name[0],b.val[0]);b.name[1]&&f.setAttribute(b.name[1],b.val[1]);var h=b.content;void 0!==h&&(f.innerHTML=h);a.appendChild(f)}};
Frame.prototype.wrapper=function(a,c,e){c=document.createElement(c);c.setAttribute(e.name,e.val);e=a[0].parentNode;for(var b=a.length,g=0;g<b;g++)c.appendChild(a[0]);e.appendChild(c)};
Frame.prototype.rowsFiller=function(a){a=this.getElementsByClassName(document.body,a);for(var c=this.toolsA.tools.length,e=this.rows-1,b=0,g=this.n/this.rows,f=0;f<c;f++)e=parseInt(f/g)%this.rows,b=document.createElement("img"),b.setAttribute("height","56px"),b.setAttribute("width","56px"),b.setAttribute("src",this.image(this.toolsA.title[f])),b.setAttribute("data-title",this.toolsA.title[f].tooltip),a[e].appendChild(b),b=parseInt(a[e].style.width,10),isNaN(parseInt(b,10))&&(b=0),a[e].style.width=
b+this.imgSize+"px"};Frame.prototype.shiftR=function(){this.animate(document.getElementById(this.index+"shift"),"left","px",this.positionY*this.current,this.positionY*(this.current+1),this.speed)};Frame.prototype.shiftL=function(){this.animate(document.getElementById(this.index+"shift"),"left","px",this.positionY*this.current,this.positionY*(this.current-1),this.speed)};
Frame.prototype.animate=function(a,c,e,b,g,f){if(a){var h=(new Date).getTime(),k=setInterval(function(){var l=Math.min(1,((new Date).getTime()-h)/f);a.style[c]=b+l*(g-b)+e;1==l&&clearInterval(k)},25);a.style[c]=b+e}};Frame.prototype.timer=function(){this.timerFlag=!1;var a=this;setTimeout(function(){a.timerFlag=!0},this.speed)};
Frame.prototype.init=function(){!0===this.arrIsNull?this.containersCreator(this.parnt,"div",1,{name:"class",val:"none",content:this.content}):(this.containersCreator(this.parnt,"div",1,{name:"id",val:this.firstSibling}),this.containersCreator(this.firstSibling,"div",1,{name:"id",val:this.secondSibling}),this.containersCreator(this.secondSibling,"div",this.rows,{name:"class name",val:this.index+"frame "}),this.toolsA.tools.length>this.n&&(this.containersCreator(this.firstSibling,"div",1,{name:"class name",
val:"forward button"}),this.containersCreator(this.firstSibling,"div",1,{name:"class name",val:"back button"})),this.wrapper(this.getElementsByClassName(document.body,this.index+"frame"),"div",{name:"id",val:this.index+"shift"}),this.rowsFiller(this.index+"frame"))};var d=document,align=[[],["darks.gif","Дети Тьмы"],["lights.gif","Дети Света"],["sumers.gif","Дети Сумерек"],["chaoss.gif","Дети Хаоса"],["light.gif","Истинный Свет"],["dark.gif","Истинная Тьма"],["sumer.gif","Нейтральные Сумерки"],["chaos.gif","Абсолютный Хаос"],["angel.gif","Ангел"]],rome_nums=" I II III IV V VI VII VIII IX X XI XII XIII XIV XV".split(" "),ach_titles=[{id:1,title:"Гладиатор"},{id:2,title:"Охотник за головами"},{id:3,title:"Солдат удачи"},{id:4,title:"Поцелуй Витель"},{id:11,title:"Разбойник"},
{id:12,title:"Слуга Локара"},{id:13,title:"Вивисектор"},{id:14,title:"Защитник"},{id:15,title:"Страж города"},{id:21,title:"Гроза мародёров"},{id:23,title:"Герой"},{id:24,title:"Легенда Подземного Мира"},{id:25,title:"Исследователь подземелий"},{id:26,title:"Кто здесь?"},{id:27,title:"Звезда Арены"},{id:5,title:"Наставник"},{id:6,title:"Ветеран"},{id:10,title:"Легенда"},{id:7,title:"Полоса Везения"},{id:8,title:"Любимец Ирдиса"},{id:9,title:"Кладоискатель"},{id:16,title:"Строитель"},{id:17,title:"Букмекер"},
{id:18,title:"Чемпион"},{id:19,title:"Искатель Приключений"},{id:45,title:"Авантюрист"},{id:20,title:"Травник"},{id:22,title:"Азартный игрок"},{id:30,title:"Лесоруб"},{id:40,title:"Рыбак"},{id:50,title:"Купец"},{id:60,title:"Шахтер"},{id:70,title:"Охотник"},{id:80,title:"Ювелир"},{id:90,title:"Ремесленник"},{id:100,title:"Алхимик"},{id:110,title:"Повар"},{id:120,title:"Плотник"},{id:130,title:"Сталевар"},{id:140,title:"Летописец"},{id:150,title:"Доктор"},{id:31,title:"Пожиратель зелий"},{id:32,title:"Ценитель напитков"},
{id:33,title:"Гурман"},{id:34,title:"Стремление к величию"},{id:35,title:"Источник слёз"},{id:36,title:"Жажда скорости"},{id:37,title:"Жажда крови"},{id:38,title:"Толстокожий"},{id:39,title:"Сила жизни"},{id:41,title:"Сила разума"},{id:42,title:"Демонолог"},{id:43,title:"Демонолог-вредитель"},{id:44,title:"Источник молодости"},{id:46,title:"Тёмные искусства"}],medal_titles=[{id:1,title:"Орден Серебряной Длани"},{id:2,title:"Орден Золотого Аранея"},{id:3,title:"Знак Стража Зимы"},{id:4,title:"Золотое Перо"},
{id:5,title:"Метка Весёлого Роджера"},{id:6,title:"Орден Лазурного Рифа"},{id:7,title:"Орден Серебряной Длани"},{id:8,title:"Орден Золотого Аранея"},{id:9,title:"Орден Серебряной Длани"},{id:10,title:"Орден Золотого Аранея"},{id:11,title:"Орден Золотого Аранея"},{id:12,title:"Орден Золотого Аранея"}];
switch_block=function(a,c){var e=document.getElementById(a),b=!0==c?1:-1,g=e.children.length;if(!(2>g))for(var f=0;f<g;f++){var h=e.children[f];if("block"===h.style.display){e=0==f&&0>b?e.children[g-1]:f==g-1&&0<b?e.children[0]:e.children[f+b];h.style.display="none";e.style.display="block";break}}};zero_put=function(a,c){var e=4,b=a.length,g=c.length;4<g&&(e=g);for(var f="";b<e;b++)f+="0";f+=a+"/";for(b=g;b<e;b++)f+="0";return f+c};
sl_view=function(a,c,e){a=a.split(":",3);var b="<b>"+a[1]+"</b>";a[2]&&(b+=sl_alts(a[2]));return"<img src=http://image.neverlands.ru/weapon/"+a[0]+" width="+c+" height="+e+" onmouseover=\"tooltip(this,'"+b+'\')" onmouseout="hide_info(this)">'};
sl_alts=function(a){var c="";a=a.split("|");a[4]=parseInt(a[4]);a[0]&&(c+=" ("+a[0]+")");0!==parseInt(a[1])&&(c+="<br>Удар: "+a[1]+"-"+a[2]);0!==parseInt(a[3])&&(c+="<br>Класс брони: +"+a[3]);0<a[4]?c+="<br>Пробой брони: +"+a[4]:0>a[4]&&(c+="<br>Пробой брони: "+a[4]);0!==parseInt(a[5])&&(c+="<br>HP: +"+a[5]);0!==parseInt(a[6])&&(c+="<br>MP: +"+a[6]);return c};
top_small=function(a){switch(a){case 1:return'<a href="http://top.mail.ru/jump?from=665202" target="_blank"><img src="http://d6.c2.ba.a0.top.mail.ru/counter?id=665202;t=69;js=13;r='+r+";j="+navigator.javaEnabled()+";s="+sfo+";d="+dep+";rand="+Math.random()+'" border="0" height="31" width="38" style="filter:alpha(opacity=50);"></a>';case 2:return'<a href="http://www.liveinternet.ru/click" target="_blank"><img src="http://counter.yadro.ru/hit?t44.2;r'+r+("undefined"==typeof s?"":";s"+sfo+"*"+dep)+";u"+
escape(d.URL)+";"+Math.random()+'" border="0" width="31" height="31" style="filter:alpha(opacity=50);"></a>'}};
view_pinfo_top=function(){var a,c=Math.round(182*hpmp[0]/hpmp[1]),e=hpmp[3]?Math.round(182*hpmp[2]/hpmp[3]):0,b=slots[0].split("@"),g=parameters[0][5].split("[");d.write('<div id="tooltip"></div><div id="main"><div id="effects">');for(a=0;a<eff.length;a++)d.write('<img src="http://image.neverlands.ru/pinfo/eff_'+eff[a][0]+'.gif" width="29" height="29" onmouseover="tooltip(this,\''+eff[a][1]+'\')" onmouseout="hide_info(this)">');d.write('</div><div id="znaki">');for(a=0;a<ability.length;a++)d.write('<img src="http://image.neverlands.ru/pinfo/t'+
ability[a][0]+'.gif" width="44" height="45" onmouseover="tooltip(this,\''+ability[a][1]+'\')" onmouseout="hide_info(this)">');d.write('</div><table cellspacing="0" cellpadding="0" border="0" width="1004px"><tr><td style="width:296px"><table class="infoblock" style="margin:105px 0 0 35px;" cellspacing="0" cellpadding="0" border="0"><tr><td class="left"><div class="top_left_left"></div></td><td class="layer"><div></div></td><td class="center" style="width:232px;"><div class="top_name_left">Характеристики</div>');
d.write('<div class="tabs_title_block"><div class="active">'+parameters[0][0]+" ["+parameters[0][3]+']</div><div>Питомец</div><div>Ездовое животное</div></div><div class="chars">');var f=0;for(a=0;a<parameters[1].length;a++)f=parameters[1][a][1]+parameters[1][a][2],d.write((a?'<div class="underline"></div>':"")+'<div class="char_item"><div>'+parameters[1][a][0]+':</div><span class="tb"><b>'+(1<f?f:1)+"</b>"+(parameters[1][a][2]?"<u>("+parameters[1][a][1]+(0<parameters[1][a][2]?"+":"")+parameters[1][a][2]+
")</u>":"")+"</span></div>");d.write('<div class="uzor"></div>');for(a=0;a<parameters[2].length;a++)d.write((a?'<div class="underline"></div>':"")+'<div class="char_item"><div>'+parameters[2][a][0]+":</div><span><strong>"+parameters[2][a][1]+"</strong></span></div>");d.write('</div></td><td class="layer"><div></div></td><td class="right"><div class="top_right_left"></div></td></tr><tr><td class="bot_left"></td><td class="bot_layer"><div></div></td><td class="bot_center"></td><td class="bot_layer"><div></div></td><td class="bot_right"></td></tr></table></td><td style="width:392px;height:508px; overflow:hidden;"><div id="top_username_block"><div id="top_username"><div><div>');
0<parameters[0][1]&&d.write("<img src=http://image.neverlands.ru/signs/"+align[parameters[0][1]][0]+" width=15 height=12 border=0 align=absmiddle onmouseover=\"tooltip(this,'"+align[parameters[0][1]][1]+'\')" onmouseout="hide_info(this)"> ');"none"!==parameters[0][2]&&d.write("<img src=http://image.neverlands.ru/signs/"+parameters[0][2]+" width=15 height=12 border=0 align=absmiddle onmouseover=\"tooltip(this,'"+parameters[0][8]+'\')" onmouseout="hide_info(this)">&nbsp;');b[16]||(b[16]="sl_l_6.gif:Слот для штанов:");
b[17]||(b[17]="sl_r_7.gif:Слот для реликвии:");b[18]||(b[18]="sl_r_5.gif:Слот для кольца:");b[19]||(b[19]="sl_r_5.gif:Слот для кольца:");d.write(parameters[0][0]+" ["+parameters[0][3]+"] <SUP>"+hpmp[4]+"%</SUP></div>");d.write("<div>Питомец<sup>100%</sup></div><div>Ездовое животное<sup>100%</sup></div></div></div></div>");d.write('<div class="character_info_center_block"><div class="top_block"></div><div class="middle_block"><div class="character_tab_content clearfix"><div class="character_things_block clearfix">');
d.write(sl_view(b[0],62,65)+sl_view(b[1],62,35)+sl_view(b[2],62,91)+sl_view(b[16],62,81)+sl_view(b[7],62,63));d.write('</div><div class="character_avatar_block"><div class="avatar_block"><img src="http://image.neverlands.ru/obrazy/'+parameters[0][4]+'" width="115" height="255" alt=""></div><div class="things_slots clearfix">');d.write(sl_view(b[13],31,31)+sl_view(b[14],31,31)+sl_view(b[18],31,31)+sl_view(b[19],31,31));d.write('</div></div><div class="character_things_block clearfix">');d.write(sl_view(b[8],
20,19)+sl_view(b[9],42,19)+sl_view(b[10],62,40)+sl_view(b[11],62,40)+sl_view(b[12],62,91)+sl_view(b[15],62,83)+sl_view(b[3],62,30)+sl_view(b[17],62,31));d.write("</div></div>");d.write('<div class="character_hp_block" style="height: '+c+"px; margin-top: "+(182-c)+'px"></div>');d.write('<div style="position: relative; left: 1px; top: 3px">'+sl_view(b[4],20,20)+"<img src=http://image.neverlands.ru/weapon/slots/1x1gr.gif width=1 height=20>"+sl_view(b[5],20,20)+"<img src=http://image.neverlands.ru/weapon/slots/1x1gr.gif width=1 height=20>"+
sl_view(b[6],20,20)+"</div>");d.write('<div class="character_mp_block" style="height: '+e+"px; margin-top: "+(182-e)+'px"></div>');d.write('<div class="character_info_bottom"><div class="hp">'+zero_put(hpmp[0].toString(),hpmp[1].toString())+'</div><div class="mp">'+zero_put(hpmp[2].toString(),hpmp[3].toString())+"</div></div>");d.write('</div><div class="bottom_block"><div class="bottom_content_block"><div>'+(parameters[0][6]?"<b>"+g[0].slice(0,-1)+"</b>"+(parameters[0][7]?' [ <a href="./logs.fcg?fid='+
parameters[0][7]+'" target=_blank style="color:#ff3036;"><b>в бою</b></a> ]':"")+"<br>"+g[1].slice(0,-1):"<b>Персонаж находится вне мира</b><br>Местоположение: неизвестно")+"</div></div></div></div></td>");d.write('<td style="width:296px"><table class="infoblock" style="margin:105px 0 0 0;" cellspacing="0" cellpadding="0" border="0"><tr><td class="left"><div class="top_left_right"></div></td><td class="layer"><div></div></td><td class="center" style="width:232px;"><div class="top_name_right">Информация</div><div class="info_text"><div class="line_text">Место рождения: <strong>'+
parameters[0][10]+'</strong></div><div class="underline"></div><div class="line_text">Дата рождения: <strong>'+parameters[0][11]+"</strong></div>"+(parameters[0][9]?'<div class="underline"></div><div class="line_text"><b>'+parameters[0][9]+"</b></div>":"")+'</div></td><td class="layer"><div></div></td><td class="right"><div class="top_right_right"></div></td></tr><tr><td class="bot_left"></td><td class="bot_layer"><div></div></td><td class="bot_center"></td><td class="bot_layer"><div></div></td><td class="bot_right"></td></tr></table>');
d.write('<table class="infoblock" style="margin:15px 0 0 0;" cellspacing="0" cellpadding="0" border="0"><tr><td class="left" style="vertical-align:middle;"></td><td id="acell" class="center" style="width:232px; padding:0 11px;"><div class="top_name_right">Достижения</div></td><td style="vertical-align:middle;" class="right"></td></tr><tr><td class="bot_left"></td><td class="bot_center"></td><td class="bot_right"></td></tr></table>');d.write('<table class="infoblock" style="margin:15px 0 0 0;" cellspacing="0" cellpadding="0" border="0"><tr><td class="left" style="vertical-align:middle;"></td><td id="mcell" class="center" style="width:232px; padding:0 11px;"><div class="top_name_right">Награды</div></td><td style="vertical-align:middle;" class="right"></td></tr><tr><td class="bot_left"></td><td class="bot_center"></td><td class="bot_right"></td></tr></table>');
d.write('</td></tr></table><div class="div"><div class="div_block"><div class="div_right"><div class="div_gr" style="width: 860px;"><div class="div_center"></div></div></div></div></div><div class="presents">');c=presents.length;for(a=0;a<c;a++)d.write("<img src=http://image.neverlands.ru/presents/"+presents[a][0]+".gif width=100 height=100 onmouseover=\"tooltip(this,'"+presents[a][1]+'\')" onmouseout="hide_info(this)">');d.write("</div>");c&&d.write('<div class="div"><div class="div_block"><div class="div_right"><div class="div_gr" style="width: 660px;"><div class="div_center2"></div></div></div></div></div>');
d.write('<table class="infoblock2" cellspacing="0" cellpadding="0" border="0"><tr><td class="left_top"><div class="top_left_right"></div></td><td class="center_top"><div class="top_name_right">Информация</div></td><td class="right_top"><div class="top_right_right"></div></td></tr><tr><td class="left_middle"></td><td class="center_middle" style="width: 660px;"><div class="chars"><div class="char_item"><div>Имя:</div><span>'+info[0]+'</span></div><div class="char_item"><div>Страна:</div><span>'+info[1]+
'</span></div><div class="char_item"><div>Город:</div><span>'+info[2]+'</span></div><div class="char_item"><div>Пол:</div><span>'+(info[3]?"Женский":"Мужской")+'</span></div><div class="char_item"><div>Домашняя страница:</div><span><a href="http://'+info[4]+'" target=_blank>'+info[4]+"</a></span></div>"+(info[5]?'<div class="char_item"><div>E-mail:</div><span>'+info[5]+"</span></div>":"")+(info[6]?'<div class="char_item"><div>Дата рождения:</div><span>'+info[6]+"</span></div>":"")+(info[7]?'<div class="char_item"><div>ICQ:</div><span>'+
info[7]+"</span></div>":"")+(info[8]?'<div class="char_item"><div>ID Персонажа:</div><span>'+info[8]+"</span></div>":"")+(info[9]?'<div class="char_item"><div>IP:</div><span>'+info[9]+"</span></div>":"")+(info[10]?'<div class="char_item"><div>Дата входа:</div><span>'+info[10]+"</span></div>":"")+(info[12]?'<div class="char_item"><div>Деньги:</div><span>'+info[12]+" NV</span></div>":"")+'</div></td><td class="right_middle"></td></tr><tr><td class="left_bot"></td><td class="center_bot"></td><td class="right_bot"></td></tr></table>');
0<info[11].length&&(d.write(PInfoPVUMenu()),PInfoCalendar());d.write('<table class="infoblock2" cellspacing="0" cellpadding="0" border="0"><tr><td class="left_top"></div></td><td class="center_top"><div class="top_name_right">О себе</div></td><td class="right_top"></td></tr><tr><td class="left_middle"></td><td class="center_middle" style="width: 660px;"><div class="text">');for(j=0;j<medals.length;j++)medals.hasOwnProperty(j)};
view_pinfo_bottom=function(){d.write('</div></td><td class="right_middle"></td></tr><tr><td class="left_bot"></td><td class="center_bot"></td><td class="right_bot"></td></tr></table></div><div id="footer"><span class="left_counter">'+top_small(1)+'</span><span class="right_counter">'+top_small(2)+'</span><div><a href="http://www.neverlands.ru/?qreg=1">Регистрация</a> <img  src="http://image.neverlands.ru/pinfo/sep.jpg" alt="" /> <a href="http://forum.neverlands.ru">Форум</a> <img  src="http://image.neverlands.ru/pinfo/sep.jpg" alt="" /> <a href="http://wiki.neverlands.ru">Библиотека</a> <br />© Copyright 2004-2024, Neverlands LLC. Все права защищены.</div></div>');
var a=new Frame({index:"a",arr:achievements,titles:ach_titles,imgNumber:12,imgSize:58,rowsNumber:3,speed:400,shiftPx:-232,eventContainerId:"acell",parnt:"acell",firstSibling:"ach",secondSibling:"achievements",content:"нет достижений",image:function(a){return"http://image.neverlands.ru/achievement/"+a.id+"/a_"+a.id+"_"+a.level+".gif"}}),c=new Frame({index:"m",arr:medals,titles:medal_titles,imgNumber:4,imgSize:58,rowsNumber:1,speed:400,shiftPx:-232,eventContainerId:"mcell",parnt:"mcell",firstSibling:"med",
secondSibling:"medals",content:"нет наград",image:function(a){return"http://image.neverlands.ru/medal/"+a.id+"/m_"+a.id+"_"+a.level+".gif"}});a.init();c.init()};view_pinfo_error=function(){};var d=document,s=screen,sfo=s.width+"*"+s.height,dep=s.colorDepth?s.colorDepth:s.pixelDepth,r=escape(d.referrer);function view_t(){return'<a href="http://top.mail.ru/jump?from=665202" target="_blank"><img src="http://d6.c2.ba.a0.top.mail.ru/counter?id=665202;t=79;js=13;r='+r+";j="+navigator.javaEnabled()+";s="+sfo+";d="+dep+";rand="+Math.random()+'" border="0" height="31" width="38" style="filter:alpha(opacity=50);"></a>'};var d=document,offsetfromcursorY=15,ie=d.all&&!window.opera,ns6=d.getElementById&&!d.all,tipobj,op,v=0;function tooltip(a,c){tipobj=d.getElementById("tooltip");tipobj.innerHTML=c;op=1;tipobj.style.opacity=op;a.onmousemove=positiontip;appear()}function hide_info(a){tipobj.style.visibility="hidden";a.onmousemove="";v=0}function ietruebody(){return d.compatMode&&"BackCompat"!=d.compatMode?d.documentElement:d.body}
function positiontip(a){v||(v=1,tipobj.style.visibility="visible");var c=ns6?a.pageX:event.clientX+ietruebody().scrollLeft,e=ns6?a.pageY:event.clientY+ietruebody().scrollTop,b=ie?ietruebody().clientWidth:window.innerWidth-20,g=ie?ietruebody().clientHeight:window.innerHeight-20,g=ie?g-event.clientY-offsetfromcursorY:g-a.clientY-offsetfromcursorY;tipobj.style.left=(ie?b-event.clientX:b-a.clientX)<tipobj.offsetWidth?c-tipobj.offsetWidth+"px":c+"px";tipobj.style.top=g<tipobj.offsetHeight?e-tipobj.offsetHeight-
offsetfromcursorY+"px":e+offsetfromcursorY+"px"}function appear(){1>op&&(op+=.1,tipobj.style.opacity=op,tipobj.style.filter="alpha(opacity="+100*op+")",t=setTimeout("appear()",30))};
