package ru.neverlands.anclient.postfilter;

import android.content.Context;

import java.nio.charset.Charset;

import ru.neverlands.anclient.utils.AppLog;
import ru.neverlands.anclient.utils.Russian;

/** Adds ANClient bridge guards to the server mine script without replacing the original script. */
public final class MineJs {
    private static final String TAG = "MineJs";
    private static final Charset WINDOWS_1251 = Charset.forName("windows-1251");
    private static final String MARKER = "/*ANCLIENT_MINE_RUNTIME_PATCH*/";

    private static final String PATCH = lines(
            MARKER,
            "(function(){",
            "if(window.__an_mine_patch_applied)return;",
            "window.__an_mine_patch_applied=true;",
            "var __an=(typeof window.AndroidBridge!=='undefined')?window.AndroidBridge:null;",
            "if(typeof window.external==='undefined'&&__an)window.external=__an;",
            "function bridge(){return (typeof window.external!=='undefined')?window.external:__an;}",
            "function tr(m){try{if(__an&&__an.TraceAutoMineRuntime)__an.TraceAutoMineRuntime(String(m));}catch(e){}}",
            "function callBridge(code){try{if(__an&&__an.DoMineAutoDig)return !!__an.DoMineAutoDig(String(code||''));}catch(e){}return false;}",
            "function autoDigWaitMs(){try{var b=bridge();if(b&&b.getMineAutoDigWaitMs)return Math.max(0,toInt(b.getMineAutoDigWaitMs(),0));}catch(e){tr('auto dig wait error '+e);}return 0;}",
            "if(typeof window.__anMineAutoDigTimer==='undefined')window.__anMineAutoDigTimer=0;",
            "function scheduleAutoDigRetry(source,wait){try{wait=toInt(wait,1000);if(wait<250)wait=250;if(wait>600000)wait=600000;if(window.__anMineAutoDigTimer){clearTimeout(window.__anMineAutoDigTimer);window.__anMineAutoDigTimer=0;}source=String(source||'view_mine').replace(/(:timer)+$/,'');window.__anMineAutoDigTimer=setTimeout(function(){window.__anMineAutoDigTimer=0;try{window.__anTryAutoMineDig(source+':timer');}catch(e){tr('auto dig retry error '+e);}},wait);}catch(e){tr('auto dig schedule error '+e);}}",
            "function findDiggCode(){",
            " var pools=[];",
            " try{if(typeof mapbt!=='undefined'&&mapbt)pools.push(mapbt);}catch(e){}",
            " try{if(typeof bavail!=='undefined'&&bavail)pools.push(bavail);}catch(e){}",
            " try{if(typeof buttons!=='undefined'&&buttons)pools.push(buttons);}catch(e){}",
            " for(var p=0;p<pools.length;p++){var a=pools[p];for(var i=0;i<a.length;i++){try{if(a[i]&&a[i][0]==='digg')return a[i][2]||a[i][1]||'';}catch(e){}}}",
            " return '';",
            "}",
            "function toInt(v,d){var n=parseInt(v,10);return isNaN(n)?d:n;}",
            "function cellSizeValue(){return (typeof cellSize==='number'&&cellSize>0)?cellSize:130;}",
            "function currentX(){try{return toInt(pos[1],0);}catch(e){return 0;}}",
            "function currentY(){try{return toInt(pos[0],0);}catch(e){return 0;}}",
            "function currentLvl(){try{return String(pos[2]||'');}catch(e){return '';}}",
            "function isTunnelView(){try{return toInt(pos[2],0)>0;}catch(e){return false;}}",
            "function timerMs(v){var n=toInt(v,-1);if(n<0)return -1;return (n>0&&n<10000)?n*1000:n;}",
            "function reportNeverTimer(v,source){var ms=timerMs(v);if(ms<0)return;try{var b=bridge();if(b&&b.SetNeverTimer)b.SetNeverTimer(ms);tr('SetNeverTimer '+ms+' source='+source);}catch(e){tr('SetNeverTimer error '+e);}}",
            "function routeWaitMs(){var wait=0,why=[];try{var tl=toInt(time_left,0);if(tl>0){wait=Math.max(wait,tl+350);why.push('time_left='+tl);}}catch(e){}try{if(typeof disable_move!=='undefined'&&disable_move){wait=Math.max(wait,1000);why.push('disable_move=true');}}catch(e){}try{if(typeof moving_status!=='undefined'&&toInt(moving_status,0)!==0){wait=Math.max(wait,1000);why.push('moving_status='+toInt(moving_status,0));}}catch(e){}routeWaitMs.reason=why.join(',');return wait;}",
            "function fallbackCell(x,y){return '<span style=\"color:white;font-weight:bold;font-size:10px;text-shadow:black 1px 1px 0,black -1px -1px 0,black -1px 1px 0,black 1px -1px 0;position:absolute;top:50px;width:130px;text-align:center;z-index:2;\">'+x+'-'+y+'</span>';}",
            "function bridgeCellHtml(x,y){try{var b=bridge();if(b&&b.getMineCellHTML)return String(b.getMineCellHTML(String(x),String(y),currentLvl())||'');}catch(e){tr('cell html error '+e);}return '';}",
            "function syncMinePosition(source){try{var b=bridge();if(b&&b.getNextMineMoveDirection)b.getNextMineMoveDirection(String(currentX()),String(currentY()),currentLvl(),'sync:'+String(source||''));}catch(e){tr('position sync error '+e);}}",
            "function ensureMineStyles(){try{if(document.getElementById('anMineRouteStyle'))return;var style=document.createElement('style');style.id='anMineRouteStyle';style.type='text/css';style.appendChild(document.createTextNode('@keyframes anMineRouteBlink{0%{box-shadow:0 0 0 2px rgba(255,42,42,.35) inset;}100%{box-shadow:0 0 0 5px rgba(255,42,42,1) inset;}} .an-mine-route-blink{animation:anMineRouteBlink .75s infinite alternate;}'));(document.head||document.documentElement).appendChild(style);}catch(e){tr('style error '+e);}}",
            "var __anMineServerCellImages={};",
            "function bridgeCellImg(x,y){try{var b=bridge();if(b&&b.getCellImg){var img=String(b.getCellImg(String(x),String(y))||'');if(img)return img;}}catch(e){tr('cell img error '+e);}return serverCellImg(x,y);}",
            "function resolveMineImg(img){",
            " img=String(img||'').replace(/^\\s+|\\s+$/g,'');",
            " if(!img)return '';",
            " if(/^https?:\\/\\//i.test(img)||img.charAt(0)==='/')return img;",
            " if(/\\.(jpg|jpeg|gif|png|webp)$/i.test(img))return 'http://image.neverlands.ru/gameplay/mine_new/'+img;",
            " return 'http://image.neverlands.ru/gameplay/mine_new/'+img+'.jpg';",
            "}",
            "function stripCssUrl(value){",
            " value=String(value||'');",
            " var m=value.match(/url\\([\"']?([^\"')]+)[\"']?\\)/i);",
            " return m?m[1]:'';",
            "}",
            "function collectMineCellImages(root){",
            " var result=[];",
            " if(!root)return result;",
            " var td=root.getElementsByTagName('TD');",
            " for(var i=0;i<td.length;i++){",
            "  var bg=td[i].style.backgroundImage||td[i].style.background||'';",
            "  try{if(!bg&&window.getComputedStyle)bg=getComputedStyle(td[i]).backgroundImage||'';}catch(e){}",
            "  var url=stripCssUrl(bg);",
            "  if(url&&url.indexOf('/gameplay/mine_new/')>=0)result.push(url);",
            " }",
            " return result;",
            "}",
            "function collectMineImages(root){",
            " var result=collectMineCellImages(root);",
            " if(result.length)return result;",
            " if(!root)return result;",
            " var img=root.getElementsByTagName('IMG');",
            " for(var j=0;j<img.length;j++){var src=String(img[j].src||'');if(src.indexOf('/gameplay/mine_new/')>=0)result.push(src);}",
            " return result;",
            "}",
            "function captureServerCellImages(){",
            " var root=document.getElementById('tunnels_div')||document.getElementById('content');",
            " var images=collectMineImages(root);",
            " if(!images.length)return;",
            " var cx=currentX(),cy=currentY();",
            " var side=Math.round(Math.sqrt(images.length));",
            " if(side*side!==images.length){side=images.length>=9?3:1;images=images.slice(0,side*side);}",
            " var radius=Math.floor(side/2);",
            " for(var i=0;i<images.length;i++){var x=cx+(i%side)-radius;var y=cy+Math.floor(i/side)-radius;__anMineServerCellImages[x+'-'+y]=images[i];}",
            " tr('captured server mine images count='+images.length+' side='+side+' known='+Object.keys(__anMineServerCellImages).length);",
            "}",
            "function serverCellImg(x,y){return __anMineServerCellImages[String(x)+'-'+String(y)]||'';}",
            "function isAnScalableNode(node){try{return !!(node&&node.getAttribute&&node.getAttribute('data-an-scalable-mine')==='1');}catch(e){return false;}}",
            "function findAncestorById(node,id){while(node){if(node.id===id)return node;node=node.parentNode;}return null;}",
            "function findDescById(root,id){if(!root)return null;if(root.id===id)return root;var all=root.getElementsByTagName?root.getElementsByTagName('*'):[];for(var i=0;i<all.length;i++){if(all[i].id===id)return all[i];}return null;}",
            "function detachServerMineDom(){var div=document.getElementById('tunnels_div');var main=div?findAncestorById(div,'main_tunnels'):null;var fallback=document.getElementById('main_tunnels');if(!main&&fallback&&!isAnScalableNode(fallback))main=fallback;if(main&&main.parentNode)main.parentNode.removeChild(main);return main;}",
            "function buildCompatServerMineDom(){var main=document.createElement('DIV');main.id='main_tunnels';var tdiv=document.createElement('DIV');tdiv.id='tunnels';main.appendChild(tdiv);var light=document.createElement('DIV');var lightmap=document.createElement('MAP');lightmap.id='lightmap';lightmap.name='lightmap';light.appendChild(lightmap);tdiv.appendChild(light);var div=document.createElement('DIV');div.id='tunnels_div';tdiv.appendChild(div);var table=document.createElement('TABLE');table.border=0;table.cellPadding=0;table.cellSpacing=0;div.appendChild(table);var tbody=document.createElement('TBODY');table.appendChild(tbody);for(var r=0;r<3;r++){var trEl=document.createElement('TR');for(var c=0;c<3;c++){var td=document.createElement('TD');var img=document.createElement('IMG');img.src='http://image.neverlands.ru/1x1.gif';img.width=130;img.height=130;td.appendChild(img);trEl.appendChild(td);}tbody.appendChild(trEl);}window.lightmap=lightmap;window.div_tunnels=div;return main;}",
            "function ensureServerMineDom(contentDiv,serverMain){try{if(!serverMain)serverMain=buildCompatServerMineDom();serverMain.style.position='absolute';serverMain.style.left='-10000px';serverMain.style.top='-10000px';serverMain.style.width='390px';serverMain.style.height='390px';serverMain.style.overflow='hidden';serverMain.style.pointerEvents='none';serverMain.style.opacity='0.01';serverMain.style.display='block';contentDiv.appendChild(serverMain);var div=findDescById(serverMain,'tunnels_div');var lm=findDescById(serverMain,'lightmap');if(div)window.div_tunnels=div;if(lm)window.lightmap=lm;tr('server mine dom preserved');}catch(e){tr('server mine dom preserve error '+e);}}",
            "function stripInlineOnClick(html){return String(html||'').replace(/\\s+onclick=\"[^\"]*\"/ig,'').replace(/\\s+onclick='[^']*'/ig,'');}",
            "function mineDirectionTo(x,y){var dx=toInt(x,0)-currentX();var dy=toInt(y,0)-currentY();if(dx===1&&dy===0)return 'right';if(dx===-1&&dy===0)return 'left';if(dx===0&&dy===1)return 'down';if(dx===0&&dy===-1)return 'up';return '';}",
            "if(typeof window.__anMineRouteLastAt!=='number')window.__anMineRouteLastAt=0;",
            "if(typeof window.__anMineRouteTimer==='undefined')window.__anMineRouteTimer=0;",
            "if(typeof window.__anMineAcceptedMoveDir==='undefined')window.__anMineAcceptedMoveDir='';",
            "if(typeof window.__anMineLastDispatchedDir==='undefined')window.__anMineLastDispatchedDir='';",
            "function routeSource(source){return String(source||'route').replace(/(:timer)+$/,'');}",
            "function mineDirDelta(dir){dir=String(dir||'').toLowerCase();if(dir==='right')return[1,0];if(dir==='left')return[-1,0];if(dir==='down')return[0,1];if(dir==='up')return[0,-1];return[0,0];}",
            "function rememberAcceptedMove(dir,source){dir=String(dir||'').toLowerCase();var d=mineDirDelta(dir);if(!dir||(!d[0]&&!d[1]))return;window.__anMineAcceptedMoveDir=dir;window.__anMineLastDispatchedDir='';tr('route accepted move '+dir+' source='+source);}",
            "function applyAcceptedMove(source){try{var dir=String(window.__anMineAcceptedMoveDir||'').toLowerCase();var d=mineDirDelta(dir);if(!dir||(!d[0]&&!d[1]))return false;if(typeof pos==='undefined'||!pos||pos.length<2)return false;pos[1]=toInt(pos[1],0)+d[0];pos[0]=toInt(pos[0],0)+d[1];window.__anMineAcceptedMoveDir='';tr('route advanced pos '+currentX()+'/'+currentY()+' dir='+dir+' source='+source);syncMinePosition('advance:'+source);updateMoveText();return true;}catch(e){tr('advance pos error '+e);return false;}}",
            "function resetMineMoveState(source){try{if(typeof moving_status!=='undefined'&&toInt(moving_status,0)!==0){moving_status=0;tr('route reset moving_status source='+source);}}catch(e){}try{if(typeof time_left!=='undefined'&&toInt(time_left,0)<=0)time_left=0;}catch(e){}}",
            "function hasPendingMineRoute(){try{var b=bridge();if(b&&b.hasPendingMineRoute)return !!b.hasPendingMineRoute();}catch(e){tr('route pending check error '+e);}return false;}",
            "function bridgeNextRouteDirection(source){try{var b=bridge();if(b&&b.getNextMineMoveDirection)return String(b.getNextMineMoveDirection(String(currentX()),String(currentY()),currentLvl(),String(source||''))||'');}catch(e){tr('route bridge error '+e);}return '';}",
            "function markMoveDispatch(dir,source){try{var b=bridge();if(b&&b.MarkMineRouteMoveDispatched)b.MarkMineRouteMoveDispatched(String(currentX()),String(currentY()),currentLvl(),String(dir||''),String(source||''));}catch(e){tr('mark dispatch error '+e);}}",
            "function dispatchMineMove(dir,source,label){try{if(typeof move_tunnels!=='function'){tr('route move_tunnels missing source='+source);return false;}if(Date.now()-window.__anMineRouteLastAt<500)return false;window.__anMineRouteLastAt=Date.now();window.__anMineLastDispatchedDir=String(dir||'');markMoveDispatch(dir,source);tr((label||'route move_tunnels')+' '+dir+' source='+source);move_tunnels(dir);return true;}catch(e){tr('dispatch move error '+e);return false;}}",
            "function runMineRouteStep(source){try{source=routeSource(source);syncMinePosition('route:'+source);if(!hasPendingMineRoute())return;var wait=routeWaitMs();if(wait>0){tr('route waits timer '+wait+(routeWaitMs.reason?' reason='+routeWaitMs.reason:'')+' source='+source);scheduleMineRouteStep(source+':timer',wait);return;}var dir=bridgeNextRouteDirection(source);updateMoveText();if(!dir)return;dispatchMineMove(dir,source,'route move_tunnels');}catch(e){tr('route step error '+e);}}",
            "function scheduleMineRouteStep(source,delay){try{if(window.__anMineRouteTimer){clearTimeout(window.__anMineRouteTimer);window.__anMineRouteTimer=0;}source=routeSource(source);window.__anMineRouteTimer=setTimeout(function(){window.__anMineRouteTimer=0;try{if(!isTunnelView())return;runMineRouteStep(source);}catch(e){tr('route schedule error '+e);}},delay||500);}catch(e){tr('route schedule setup error '+e);}}",
            "window.__anRunMineRouteStep=runMineRouteStep;window.__anScheduleMineRouteStep=scheduleMineRouteStep;",
            "function tryMineCellClick(x,y,e){",
            " try{if(Date.now()<((window.__anMineSuppressClickUntil)||0))return false;var wait=routeWaitMs();if(wait>0){var bb=bridge();if(bb&&bb.mineMoveTo){tr('manual waits timer '+wait+(routeWaitMs.reason?' reason='+routeWaitMs.reason:'')+' target='+x+'/'+y);bb.mineMoveTo(String(x),String(y));updateMoveText();scheduleMineRouteStep('manual_click_wait',wait);}return false;}var dir=mineDirectionTo(x,y);if(dir){dispatchMineMove(dir,'manual_click','manual move_tunnels');return false;}var b=bridge();if(b&&b.mineMoveTo){try{if(b.getNextMineMoveDirection)b.getNextMineMoveDirection(String(currentX()),String(currentY()),currentLvl(),'manual_click_sync');}catch(ignore){}tr('manual mineMoveTo target='+x+'/'+y);var next=String(b.mineMoveTo(String(x),String(y))||'');updateMoveText();if(next){scheduleMineRouteStep('manual_route',100);}}}catch(ex){tr('mine click error '+ex);}return false;",
            "}",
            "function updateMoveText(){",
            " var textDiv=document.getElementById('textDiv');",
            " if(!textDiv)return;",
            " try{var b=bridge();if(b&&b.getMoveText)textDiv.innerHTML=String(b.getMoveText()||'');}catch(e){tr('move text error '+e);}",
            "}",
            "function ensureCenterButton(){",
            " var place=document.getElementById('ButtonPlace');",
            " if(!place||document.getElementById('anMineCenterBtn'))return;",
            " var btn=document.createElement('input');",
            " btn.type='button';btn.className='fr_but';btn.id='anMineCenterBtn';btn.value='Где я?';",
            " btn.onclick=function(){try{window.__anMineScrollToElement();}catch(e){tr('center error '+e);}};",
            " place.appendChild(document.createTextNode(' '));place.appendChild(btn);",
            "}",
            "function buildCell(x,y){",
            " var size=cellSizeValue();",
            " var td=document.createElement('TD');",
            " td.style.width=size+'px';td.style.height=size+'px';td.style.position='relative';td.style.cursor='pointer';td.style.overflow='hidden';td.style.backgroundColor='#101010';",
            " var img=resolveMineImg(bridgeCellImg(x,y));",
            " if(img)td.style.backgroundImage='url('+img+')';",
            " td.style.backgroundPosition='center center';td.style.backgroundRepeat='no-repeat';td.style.backgroundSize='cover';",
            " td.onclick=function(e){return tryMineCellClick(x,y,e);};",
            " td.ontouchend=function(e){try{if(Date.now()<((window.__anMineSuppressClickUntil)||0))return false;if(window.moved)return false;if(e&&e.preventDefault)e.preventDefault();var handled=tryMineCellClick(x,y,e);window.__anMineSuppressClickUntil=Date.now()+350;return handled;}catch(ex){tr('mine touch error '+ex);}return false;};",
            " var html=stripInlineOnClick(bridgeCellHtml(x,y));",
            " td.innerHTML=html||fallbackCell(x,y);",
            " return td;",
            "}",
            "function renderScalableTunnels(){",
            " if(!isTunnelView())return false;",
            " var contentDiv=document.getElementById('content');",
            " if(!contentDiv)return false;",
            " ensureMineStyles();syncMinePosition('render');",
            " ensureCenterButton();",
            " var serverMain=detachServerMineDom();",
            " contentDiv.innerHTML='';contentDiv.align='center';ensureServerMineDom(contentDiv,serverMain);",
            " var textDiv=document.createElement('DIV');",
            " textDiv.id='textDiv';",
            " textDiv.style.cssText='width:210px;position:absolute;margin-top:50px;margin-left:50%;left:-105px;top:0;z-index:1;font-family:Verdana;font-size:14px;color:white;font-weight:bold;text-shadow:black 1px 1px 0,black -1px -1px 0,black -1px 1px 0,black 1px -1px 0;';",
            " contentDiv.appendChild(textDiv);",
            " var mdiv=document.createElement('DIV');",
            " mdiv.id='an_main_tunnels';mdiv.setAttribute('data-an-scalable-mine','1');mdiv.style.width='98%';mdiv.style.height='calc(100vh - 85px)';mdiv.style.overflow='hidden';mdiv.style.position='relative';mdiv.style.touchAction='none';",
            " contentDiv.appendChild(mdiv);",
            " window.__anMineVisibleTunnels=mdiv;",
            " var table=document.createElement('TABLE');",
            " var size=cellSizeValue();",
            " table.style.width=(21*size)+'px';table.style.position='absolute';table.style.left='0px';table.style.top='0px';table.style.transformOrigin='0 0';",
            " table.border=0;table.cellPadding=0;table.cellSpacing=0;",
            " mdiv.appendChild(table);",
            " var tbody=document.createElement('TBODY');table.appendChild(tbody);",
            " for(var row=0;row<=20;row++){var trEl=document.createElement('TR');for(var col=0;col<=20;col++){trEl.appendChild(buildCell(col,row));}tbody.appendChild(trEl);}",
            " if(window.__anMineDragDrop&&window.__anMineDragDrop.init)window.__anMineDragDrop.init(table);",
            " window.__anMineScrollToElement();updateMoveText();",
            " tr('scalable mine rendered pos='+currentX()+'/'+currentY());",
            " return true;",
            "}",
            "window.__anMineScrollToElement=function(){",
            " var container=document.getElementById('an_main_tunnels');",
            " if(!container||!container.firstChild)return;",
            " var table=container.firstChild;",
            " var spans=container.getElementsByTagName('SPAN');for(var i=0;i<spans.length;i++)spans[i].style.fontSize='10px';",
            " table.style.transform='scale(1)';if(window.__anMineDragDrop)window.__anMineDragDrop.scale=1;",
            " var size=cellSizeValue();",
            " var width=document.documentElement.clientWidth||window.innerWidth||760;",
            " var height=document.documentElement.clientHeight||window.innerHeight||600;",
            " table.style.left=(Math.round(width*0.49)-size*currentX()-size/2)+'px';",
            " table.style.top=((height-85)/2-size*currentY()-size/2)+'px';",
            " updateMoveText();",
            "};",
            "window.__anMineDragDrop={",
            " init:function(container){",
            "  this.moveState=false;this.x0=0;this.y0=0;this.elmX0=0;this.elmY0=0;this.container=container;this.scale=1;this.pinchStart=0;this.startScale=1;",
            "  var self=this;",
            "  container.onmousedown=function(e){self.initMove(e);};",
            "  document.onmouseup=function(){self.moveState=false;};",
            "  document.onmousemove=function(e){self.handlerMove(e);};",
            "  container.onwheel=function(e){self.handleWheel(e.deltaY<0?1:-1);if(e.preventDefault)e.preventDefault();};",
            "  container.ontouchstart=function(e){self.initMove(e);};",
            "  container.ontouchmove=function(e){self.handlerMove(e);};",
            "  container.ontouchend=function(){self.moveState=false;self.pinchStart=0;};",
            " },",
            " point:function(e){if(e&&e.touches&&e.touches.length>0)e=e.touches[0];if(!e)e=window.event;return{x:(e.pageX||e.clientX||0),y:(e.pageY||e.clientY||0)};}",
            " ,dist:function(t){if(!t||t.length<2)return 0;var dx=t[0].pageX-t[1].pageX;var dy=t[0].pageY-t[1].pageY;return Math.sqrt(dx*dx+dy*dy);}",
            " ,initMove:function(e){window.moved=false;window.__anMineSuppressClickUntil=0;if(e&&e.touches&&e.touches.length>1){this.pinchStart=this.dist(e.touches);this.startScale=this.scale;window.__anMineSuppressClickUntil=Date.now()+250;if(e.preventDefault)e.preventDefault();return;}var p=this.point(e);this.x0=p.x;this.y0=p.y;this.elmX0=parseInt(this.container.style.left)||0;this.elmY0=parseInt(this.container.style.top)||0;this.moveState=true;if(e&&e.preventDefault)e.preventDefault();}",
            " ,handlerMove:function(e){if(e&&e.touches&&e.touches.length>1){var d=this.dist(e.touches);if(this.pinchStart>0)this.setScale(this.startScale*(d/this.pinchStart));window.__anMineSuppressClickUntil=Date.now()+250;if(e.preventDefault)e.preventDefault();return;}if(this.moveState){var p=this.point(e);var movedNow=Math.abs(p.x-this.x0)>4||Math.abs(p.y-this.y0)>4;if(movedNow){window.moved=true;window.__anMineSuppressClickUntil=Date.now()+250;}this.container.style.left=(this.elmX0+p.x-this.x0)+'px';this.container.style.top=(this.elmY0+p.y-this.y0)+'px';if(e&&e.preventDefault)e.preventDefault();}}",
            " ,handleWheel:function(delta){this.setScale(this.scale+(delta>0?0.1:-0.1));}",
            " ,setScale:function(newVal){if(newVal>1)newVal=1;if(newVal<0.5)newVal=0.5;this.scale=newVal;if(this.container)this.container.style.transform='scale('+this.scale+')';var spans=this.container?this.container.getElementsByTagName('SPAN'):[];var nv=Math.round(10+(1-this.scale)*20);for(var i=0;i<spans.length;i++)spans[i].style.fontSize=nv+'px';}",
            "};",
            "function installScalableMine(){",
            " if(window.__an_scalable_mine_installed)return;",
            " if(typeof window.show_tunnels!=='function')return;",
            " window.__an_scalable_mine_installed=true;",
            " window.__anOriginalShowTunnels=window.show_tunnels;",
            " window.show_tunnels=function(){var r;try{r=window.__anOriginalShowTunnels.apply(this,arguments);}catch(e){tr('original show_tunnels error '+e);}try{captureServerCellImages();renderScalableTunnels();scheduleMineRouteStep('show_tunnels',350);}catch(e){tr('scalable show_tunnels error '+e);}return r;};",
            " tr('show_tunnels overridden');",
            "}",
            "function installTimerHook(){try{if(window.Timer&&typeof window.Timer.start==='function'&&!window.Timer.start.__an_wrapped){var oldStart=window.Timer.start;window.Timer.start=function(sec){reportNeverTimer(sec,'Timer.start');return oldStart.apply(this,arguments);};window.Timer.start.__an_wrapped=true;tr('Timer.start wrapped');}}catch(e){tr('timer hook error '+e);}}",
            "function installMineRouteHooks(){try{installTimerHook();if(typeof window.display_move==='function'&&!window.display_move.__an_route_wrapped){var oldDisplay=window.display_move;window.display_move=function(tunn,time,dir){var accepted=String((typeof dir!=='undefined'&&dir!==null)?dir:(window.__anMineLastDispatchedDir||''));var r=oldDisplay.apply(this,arguments);rememberAcceptedMove(accepted,'display_move');return r;};window.display_move.__an_route_wrapped=true;tr('display_move wrapped');}if(typeof window.finFunction==='function'&&!window.finFunction.__an_route_wrapped){var oldFin=window.finFunction;window.finFunction=function(){var advanced=applyAcceptedMove('finFunction');var r;try{r=oldFin.apply(this,arguments);}finally{resetMineMoveState('finFunction');if(advanced){try{renderScalableTunnels();}catch(e){tr('render after advance error '+e);}}scheduleMineRouteStep('move_finish',350);}return r;};window.finFunction.__an_route_wrapped=true;tr('finFunction wrapped');}}catch(e){tr('route hook error '+e);}}",
            "window.__anTryAutoMineDig=function(source){",
            " if(window.__anAutoMineDigClicked)return;",
            " var code=findDiggCode();",
            " if(!code){tr('no digg code source='+source);return;}",
            " var wait=autoDigWaitMs();if(wait>0){tr('Digg waits timer '+wait+' source='+source);scheduleAutoDigRetry(source,wait);return;}",
            " if(!callBridge(code)){wait=autoDigWaitMs();if(wait>0){tr('Digg waits bridge timer '+wait+' source='+source);scheduleAutoDigRetry(source,wait);return;}tr('bridge rejected source='+source);return;}",
            " if(typeof Digg!=='function'){tr('Digg missing source='+source);return;}",
            " window.__anAutoMineDigClicked=true;",
            " tr('Digg auto click source='+source);",
            " Digg(code);",
            " setTimeout(function(){window.__anAutoMineDigClicked=false;},1800);",
            "};",
            "function wrapViewMine(){try{installScalableMine();installMineRouteHooks();if(typeof view_mine==='function'&&!view_mine.__an_wrapped){var old=view_mine;view_mine=function(){installScalableMine();installMineRouteHooks();var r=old.apply(this,arguments);setTimeout(function(){try{if(isTunnelView())renderScalableTunnels();updateMoveText();window.__anTryAutoMineDig('view_mine');scheduleMineRouteStep('view_mine',500);}catch(e){tr('view_mine after error '+e);}},250);return r;};view_mine.__an_wrapped=true;tr('view_mine wrapped');}}catch(e){tr('wrap error '+e);}}",
            "installTimerHook();",
            "wrapViewMine();",
            "setTimeout(wrapViewMine,300);",
            "})();");

    private MineJs() {
    }

    private static String lines(String... lines) {
        StringBuilder builder = new StringBuilder();
        for (String line : lines) {
            builder.append(line).append('\n');
        }
        return builder.toString();
    }

    public static byte[] process(Context context, byte[] array) {
        String js = array == null || array.length == 0 ? "" : Russian.getString(array);
        if (js.contains(MARKER)) {
            return array;
        }
        AppLog.i("AUTO_MINE_TRACE", TAG, "inject mine.js runtime patch, originalBytes="
                + (array == null ? 0 : array.length));
        return (js + "\n" + PATCH).getBytes(WINDOWS_1251);
    }
}
