using System.Text;

namespace ANClient.PostFilter
{
    internal static partial class Filter
    {
        private const string MineJsPatchMarker = "/*ANCLIENT_PC_MINE_RUNTIME_PATCH*/";

        private static byte[] MineJs(byte[] array)
        {
            var js = array == null || array.Length == 0 ? string.Empty : AppVars.Codepage.GetString(array);
            if (js.IndexOf(MineJsPatchMarker, System.StringComparison.Ordinal) >= 0)
                return array;

            AppLog.i(AutoMineRuntime.TraceChain, "MineJs", "inject mine.js patch, originalBytes=" + (array == null ? 0 : array.Length));
            return AppVars.Codepage.GetBytes(js + "\r\n" + BuildMineJsPatch());
        }

        private static string BuildMineJsPatch()
        {
            var sb = new StringBuilder();
            AddMineJsLine(sb, MineJsPatchMarker);
            AddMineJsLine(sb, "(function(){");
            AddMineJsLine(sb, "if(window.__ancMinePatchApplied)return;");
            AddMineJsLine(sb, "window.__ancMinePatchApplied=true;");
            AddMineJsLine(sb, "function ext(){try{return window.external;}catch(e){return null;}}");
            AddMineJsLine(sb, "function tr(m){try{var b=ext();if(b)b.TraceMineRuntime(String(m));}catch(e){}}");
            AddMineJsLine(sb, "function toInt(v,d){var n=parseInt(v,10);return isNaN(n)?d:n;}");
            AddMineJsLine(sb, "function now(){return new Date().getTime();}");
            AddMineJsLine(sb, "function curX(){try{return toInt(pos[1],0);}catch(e){return 0;}}");
            AddMineJsLine(sb, "function curY(){try{return toInt(pos[0],0);}catch(e){return 0;}}");
            AddMineJsLine(sb, "function curLvl(){try{return String(pos[2]||'');}catch(e){return '';}}");
            AddMineJsLine(sb, "function isTunnel(){try{return toInt(pos[2],0)>0;}catch(e){return false;}}");
            AddMineJsLine(sb, "function timerMs(v){var n=toInt(v,-1);if(n<0)return -1;return (n>0&&n<10000)?n*1000:n;}");
            AddMineJsLine(sb, "function reportTimer(v,s){var ms=timerMs(v);if(ms<0)return;try{var b=ext();if(b)b.SetNeverTimer(ms);tr('SetNeverTimer '+ms+' source='+s);}catch(e){tr('timer report error '+e);}}");
            AddMineJsLine(sb, "function callAutoDig(code){try{var b=ext();if(b)return !!b.DoMineAutoDig(String(code||''));}catch(e){tr('bridge dig error '+e);}return false;}");
            AddMineJsLine(sb, "function autoWait(){try{var b=ext();if(b)return Math.max(0,toInt(b.getMineAutoDigWaitMs(),0));}catch(e){tr('auto wait error '+e);}return 0;}");
            AddMineJsLine(sb, "function findDiggCode(){var pools=[];try{if(typeof mapbt!='undefined'&&mapbt)pools[pools.length]=mapbt;}catch(e){}try{if(typeof bavail!='undefined'&&bavail)pools[pools.length]=bavail;}catch(e){}try{if(typeof buttons!='undefined'&&buttons)pools[pools.length]=buttons;}catch(e){}for(var p=0;p<pools.length;p++){var a=pools[p];for(var i=0;i<a.length;i++){try{if(a[i]&&a[i][0]=='digg')return a[i][2]||a[i][1]||'';}catch(e){}}}return '';}");
            AddMineJsLine(sb, "if(typeof window.__ancMineAutoDigTimer=='undefined')window.__ancMineAutoDigTimer=0;");
            AddMineJsLine(sb, "function cleanSource(source){return String(source||'view_mine').replace(/(:timer)+$/,'');}");
            AddMineJsLine(sb, "function scheduleAutoDig(source,wait){try{wait=toInt(wait,1000);if(wait<250)wait=250;if(wait>600000)wait=600000;if(window.__ancMineAutoDigTimer){clearTimeout(window.__ancMineAutoDigTimer);window.__ancMineAutoDigTimer=0;}source=cleanSource(source);window.__ancMineAutoDigTimer=setTimeout(function(){window.__ancMineAutoDigTimer=0;try{window.__ancTryMineDig(source+':timer');}catch(e){tr('auto dig retry error '+e);}},wait);}catch(e){tr('auto dig schedule error '+e);}}");
            AddMineJsLine(sb, "window.__ancTryMineDig=function(source){try{if(window.__ancAutoMineDigClicked)return;var code=findDiggCode();if(!code){tr('no digg code source='+source);return;}var wait=autoWait();if(wait>0){tr('Digg waits timer '+wait+' source='+source);scheduleAutoDig(source,wait);return;}if(!callAutoDig(code)){wait=autoWait();if(wait>0){tr('Digg waits bridge timer '+wait+' source='+source);scheduleAutoDig(source,wait);return;}tr('bridge rejected source='+source);return;}if(typeof Digg!='function'){tr('Digg missing source='+source);return;}window.__ancAutoMineDigClicked=true;tr('Digg auto click source='+source);Digg(code);setTimeout(function(){window.__ancAutoMineDigClicked=false;},1800);}catch(e){tr('auto dig error '+e);}};");
            AddMineJsLine(sb, "function cellSizeValue(){return (typeof cellSize=='number'&&cellSize>0)?cellSize:130;}");
            AddMineJsLine(sb, "function fallbackCell(x,y){return '<span style=\"color:white;font-weight:bold;font-size:10px;text-shadow:black 1px 1px 0,black -1px -1px 0,black -1px 1px 0,black 1px -1px 0;position:absolute;top:50px;width:130px;text-align:center;z-index:2;\">'+x+'-'+y+'</span>';}");
            AddMineJsLine(sb, "function cellContent(html,size){return '<div style=\"position:relative;width:'+size+'px;height:'+size+'px;overflow:hidden;\">'+String(html||'')+'</div>';}");
            AddMineJsLine(sb, "function resolveImg(img){img=String(img||'').replace(/^\\s+|\\s+$/g,'');if(!img)return '';if(/^https?:\\/\\//i.test(img)||img.charAt(0)=='/')return img;if(/\\.(jpg|jpeg|gif|png|webp)$/i.test(img))return 'http://image.neverlands.ru/gameplay/mine_new/'+img;return 'http://image.neverlands.ru/gameplay/mine_new/'+img+'.jpg';}");
            AddMineJsLine(sb, "var __ancMineServerCellImages={};");
            AddMineJsLine(sb, "function serverCellImg(x,y){return __ancMineServerCellImages[String(x)+'-'+String(y)]||'';}");
            AddMineJsLine(sb, "function bridgeImg(x,y){try{var b=ext();if(b){var img=String(b.getCellImg(String(x),String(y))||'');if(img)return img;}}catch(e){tr('cell img error '+e);}return serverCellImg(x,y);}");
            AddMineJsLine(sb, "function bridgeHtml(x,y){try{var b=ext();if(b)return String(b.getMineCellHTML(String(x),String(y),curLvl())||'');}catch(e){tr('cell html error '+e);}return '';}");
            AddMineJsLine(sb, "function syncMinePosition(source){try{var b=ext();if(b)b.getNextMineMoveDirection(String(curX()),String(curY()),curLvl(),'sync:'+String(source||''));}catch(e){tr('position sync error '+e);}}");
            AddMineJsLine(sb, "function stripCssUrl(value){value=String(value||'');var m=value.match(/url\\([\"']?([^\"')]+)[\"']?\\)/i);return m?m[1]:'';}");
            AddMineJsLine(sb, "function collectMineCellImages(root){var result=[];if(!root)return result;var td=root.getElementsByTagName('TD');for(var i=0;i<td.length;i++){var bg=td[i].style.backgroundImage||td[i].style.background||'';try{if(!bg&&window.getComputedStyle)bg=getComputedStyle(td[i]).backgroundImage||'';}catch(e){}var url=stripCssUrl(bg);if(url&&url.indexOf('/gameplay/mine_new/')>=0)result[result.length]=url;}return result;}");
            AddMineJsLine(sb, "function collectMineImages(root){var result=collectMineCellImages(root);if(result.length)return result;if(!root)return result;var img=root.getElementsByTagName('IMG');for(var j=0;j<img.length;j++){var src=String(img[j].src||'');if(src.indexOf('/gameplay/mine_new/')>=0)result[result.length]=src;}return result;}");
            AddMineJsLine(sb, "function captureServerCellImages(){var root=document.getElementById('tunnels_div')||document.getElementById('content');var images=collectMineImages(root);if(!images.length)return;var cx=curX(),cy=curY();var side=Math.round(Math.sqrt(images.length));if(side*side!==images.length){side=images.length>=9?3:1;images=images.slice(0,side*side);}var radius=Math.floor(side/2);for(var i=0;i<images.length;i++){var x=cx+(i%side)-radius;var y=cy+Math.floor(i/side)-radius;__ancMineServerCellImages[x+'-'+y]=images[i];}tr('captured server mine images count='+images.length+' side='+side);}");
            AddMineJsLine(sb, "function isAncScalableNode(node){try{return !!(node&&node.getAttribute&&node.getAttribute('data-anc-scalable-mine')=='1');}catch(e){return false;}}");
            AddMineJsLine(sb, "function findAncestorById(node,id){while(node){if(node.id==id)return node;node=node.parentNode;}return null;}");
            AddMineJsLine(sb, "function findDescById(root,id){if(!root)return null;if(root.id==id)return root;var all=root.getElementsByTagName?root.getElementsByTagName('*'):[];for(var i=0;i<all.length;i++){if(all[i].id==id)return all[i];}return null;}");
            AddMineJsLine(sb, "function detachServerMineDom(){var div=document.getElementById('tunnels_div');var main=div?findAncestorById(div,'main_tunnels'):null;var fallback=document.getElementById('main_tunnels');if(!main&&fallback&&!isAncScalableNode(fallback))main=fallback;if(main&&main.parentNode)main.parentNode.removeChild(main);return main;}");
            AddMineJsLine(sb, "function buildCompatServerMineDom(){var main=document.createElement('DIV');main.id='main_tunnels';var tdiv=document.createElement('DIV');tdiv.id='tunnels';main.appendChild(tdiv);var light=document.createElement('DIV');var lightmap=document.createElement('MAP');lightmap.id='lightmap';lightmap.name='lightmap';light.appendChild(lightmap);tdiv.appendChild(light);var div=document.createElement('DIV');div.id='tunnels_div';tdiv.appendChild(div);var table=document.createElement('TABLE');table.border=0;table.cellPadding=0;table.cellSpacing=0;div.appendChild(table);var tbody=document.createElement('TBODY');table.appendChild(tbody);for(var r=0;r<3;r++){var trEl=document.createElement('TR');for(var c=0;c<3;c++){var td=document.createElement('TD');var img=document.createElement('IMG');img.src='http://image.neverlands.ru/1x1.gif';img.width=130;img.height=130;td.appendChild(img);trEl.appendChild(td);}tbody.appendChild(trEl);}window.lightmap=lightmap;window.div_tunnels=div;return main;}");
            AddMineJsLine(sb, "function ensureServerMineDom(contentDiv,serverMain){try{if(!serverMain)serverMain=buildCompatServerMineDom();serverMain.style.position='absolute';serverMain.style.left='-10000px';serverMain.style.top='-10000px';serverMain.style.width='390px';serverMain.style.height='390px';serverMain.style.overflow='hidden';serverMain.style.pointerEvents='none';serverMain.style.opacity='0.01';serverMain.style.display='block';contentDiv.appendChild(serverMain);var div=findDescById(serverMain,'tunnels_div');var lm=findDescById(serverMain,'lightmap');if(div)window.div_tunnels=div;if(lm)window.lightmap=lm;tr('server mine dom preserved');}catch(e){tr('server mine dom preserve error '+e);}}");
            AddMineJsLine(sb, "function stripOnclick(h){return String(h||'').replace(/\\s+onclick=\"[^\"]*\"/ig,'').replace(/\\s+onclick='[^']*'/ig,'');}");
            AddMineJsLine(sb, "function dirTo(x,y){var dx=toInt(x,0)-curX();var dy=toInt(y,0)-curY();if(dx==1&&dy==0)return 'right';if(dx==-1&&dy==0)return 'left';if(dx==0&&dy==1)return 'down';if(dx==0&&dy==-1)return 'up';return '';}");
            AddMineJsLine(sb, "function routeWait(){var w=0,why=[];try{var tl=toInt(time_left,0);if(tl>0){w=Math.max(w,tl+350);why[why.length]='time_left='+tl;}}catch(e){}try{if(typeof disable_move!='undefined'&&disable_move){w=Math.max(w,1000);why[why.length]='disable_move=true';}}catch(e){}try{if(typeof moving_status!='undefined'&&toInt(moving_status,0)!=0){w=Math.max(w,1000);why[why.length]='moving_status='+toInt(moving_status,0);}}catch(e){}routeWait.reason=why.join(',');return w;}");
            AddMineJsLine(sb, "if(typeof window.__ancMineRouteTimer=='undefined')window.__ancMineRouteTimer=0;");
            AddMineJsLine(sb, "if(typeof window.__ancMineRouteLastAt!='number')window.__ancMineRouteLastAt=0;");
            AddMineJsLine(sb, "if(typeof window.__ancMineAcceptedMoveDir=='undefined')window.__ancMineAcceptedMoveDir='';");
            AddMineJsLine(sb, "if(typeof window.__ancMineLastDispatchedDir=='undefined')window.__ancMineLastDispatchedDir='';");
            AddMineJsLine(sb, "function routeSource(source){return String(source||'route').replace(/(:timer)+$/,'');}");
            AddMineJsLine(sb, "function delta(dir){dir=String(dir||'').toLowerCase();if(dir=='right')return[1,0];if(dir=='left')return[-1,0];if(dir=='down')return[0,1];if(dir=='up')return[0,-1];return[0,0];}");
            AddMineJsLine(sb, "function rememberAcceptedMove(dir,source){dir=String(dir||'').toLowerCase();var d=delta(dir);if(!dir||(!d[0]&&!d[1]))return;window.__ancMineAcceptedMoveDir=dir;window.__ancMineLastDispatchedDir='';tr('route accepted move '+dir+' source='+source);}");
            AddMineJsLine(sb, "function updateMoveText(){try{var d=document.getElementById('ancMineText');var b=ext();if(d&&b)d.innerHTML=String(b.getMoveText()||'');}catch(e){tr('move text error '+e);}}");
            AddMineJsLine(sb, "function applyAcceptedMove(source){try{var dir=String(window.__ancMineAcceptedMoveDir||'').toLowerCase();var d=delta(dir);if(!dir||(!d[0]&&!d[1]))return false;if(typeof pos=='undefined'||!pos||pos.length<2)return false;pos[1]=toInt(pos[1],0)+d[0];pos[0]=toInt(pos[0],0)+d[1];window.__ancMineAcceptedMoveDir='';tr('route advanced pos '+curX()+'/'+curY()+' dir='+dir+' source='+source);syncMinePosition('advance:'+source);updateMoveText();return true;}catch(e){tr('advance pos error '+e);return false;}}");
            AddMineJsLine(sb, "function resetMoveState(source){try{if(typeof moving_status!='undefined'&&toInt(moving_status,0)!=0){moving_status=0;tr('route reset moving_status source='+source);}}catch(e){}try{if(typeof time_left!='undefined'&&toInt(time_left,0)<=0)time_left=0;}catch(e){}}");
            AddMineJsLine(sb, "function hasRoute(){try{var b=ext();if(b)return !!b.hasPendingMineRoute();}catch(e){tr('has route error '+e);}return false;}");
            AddMineJsLine(sb, "function hasFloorExit(){try{var b=ext();if(b)return !!b.hasMineFloorExit();}catch(e){tr('has floor exit error '+e);}return false;}");
            AddMineJsLine(sb, "function nextDir(source){try{var b=ext();if(b)return String(b.getNextMineMoveDirection(String(curX()),String(curY()),curLvl(),String(source||''))||'');}catch(e){tr('next dir error '+e);}return '';}");
            AddMineJsLine(sb, "function startFloorExit(){try{var b=ext();if(!b){tr('floor exit bridge missing');return false;}tr('floor exit route start');var n=String(b.mineMoveToFloorExit()||'');updateMoveText();rerenderRoute('floor_exit');if(n)window.__ancScheduleMineRouteStep('floor_exit',100);}catch(e){tr('floor exit error '+e);}return false;}");
            AddMineJsLine(sb, "function markDispatch(dir,source){try{var b=ext();if(b)b.MarkMineRouteMoveDispatched(String(curX()),String(curY()),curLvl(),String(dir||''),String(source||''));}catch(e){tr('mark dispatch error '+e);}}");
            AddMineJsLine(sb, "function dispatchMove(dir,source,label){try{if(typeof move_tunnels!='function'){tr('move_tunnels missing source='+source);return false;}if(now()-window.__ancMineRouteLastAt<500)return false;window.__ancMineRouteLastAt=now();window.__ancMineLastDispatchedDir=String(dir||'');markDispatch(dir,source);tr((label||'route move_tunnels')+' '+dir+' source='+source);move_tunnels(dir);return true;}catch(e){tr('dispatch error '+e);return false;}}");
            AddMineJsLine(sb, "function runRoute(source){try{source=routeSource(source);syncMinePosition('route:'+source);if(!hasRoute())return;var w=routeWait();if(w>0){tr('route waits timer '+w+(routeWait.reason?' reason='+routeWait.reason:'')+' source='+source);window.__ancScheduleMineRouteStep(source+':timer',w);return;}var d=nextDir(source);updateMoveText();if(d)dispatchMove(d,source,'route move_tunnels');}catch(e){tr('route error '+e);}}");
            AddMineJsLine(sb, "window.__ancRunMineRouteStep=runRoute;window.__ancScheduleMineRouteStep=function(source,delay){try{if(window.__ancMineRouteTimer){clearTimeout(window.__ancMineRouteTimer);window.__ancMineRouteTimer=0;}source=routeSource(source);window.__ancMineRouteTimer=setTimeout(function(){window.__ancMineRouteTimer=0;try{if(!isTunnel())return;runRoute(source);}catch(e){tr('route schedule error '+e);}},delay||500);}catch(e){tr('route schedule setup error '+e);}};");
            AddMineJsLine(sb, "function rerenderRoute(source){try{renderMine();}catch(e){tr('render route error '+source+' '+e);}}");
            AddMineJsLine(sb, "function clickCell(x,y,e){try{if(now()<((window.__ancMineSuppressClickUntil)||0))return false;var w=routeWait();if(w>0){var bb=ext();if(bb){tr('manual waits timer '+w+(routeWait.reason?' reason='+routeWait.reason:'')+' target='+x+'/'+y);bb.mineMoveTo(String(x),String(y));updateMoveText();rerenderRoute('manual_wait');window.__ancScheduleMineRouteStep('manual_click_wait',w);}return false;}var d=dirTo(x,y);if(d){dispatchMove(d,'manual_click','manual move_tunnels');return false;}var b=ext();if(b){try{b.getNextMineMoveDirection(String(curX()),String(curY()),curLvl(),'manual_click_sync');}catch(ignore){}tr('manual mineMoveTo target='+x+'/'+y);var n=String(b.mineMoveTo(String(x),String(y))||'');updateMoveText();rerenderRoute('manual_route');if(n)window.__ancScheduleMineRouteStep('manual_route',100);}}catch(ex){tr('mine click error '+ex);}return false;}");
            AddMineJsLine(sb, "function ensureMineStyles(){try{if(document.getElementById('ancMineRouteStyle'))return;var style=document.createElement('style');style.id='ancMineRouteStyle';style.type='text/css';style.appendChild(document.createTextNode('@keyframes ancMineCurrentBlink{0%{box-shadow:0 0 0 2px rgba(255,255,0,.35) inset;}100%{box-shadow:0 0 0 6px rgba(255,255,0,1) inset;}} .anc-mine-current-blink{animation:ancMineCurrentBlink .75s infinite alternate;} .anc-mine-modern-btn{appearance:none!important;-webkit-appearance:none!important;border:1px solid rgba(130,255,178,.62)!important;border-radius:14px!important;background:#11984b!important;background:linear-gradient(135deg,#19bb62,#0b7c3a)!important;color:#fff!important;padding:6px 14px!important;margin:2px 4px!important;font-family:Verdana,Arial,sans-serif!important;font-size:12px!important;font-weight:700!important;letter-spacing:.2px!important;box-shadow:0 6px 16px rgba(0,0,0,.28),inset 0 1px 0 rgba(255,255,255,.26)!important;text-shadow:0 1px 1px rgba(0,0,0,.45)!important;cursor:pointer!important;transition:transform .12s ease,filter .12s ease,box-shadow .12s ease!important;} .anc-mine-modern-btn:hover{filter:brightness(1.08)!important;box-shadow:0 8px 20px rgba(0,0,0,.34),0 0 0 2px rgba(90,255,150,.18)!important;} .anc-mine-modern-btn:active{transform:translateY(1px) scale(.98)!important;}'));var head=document.getElementsByTagName('head')[0]||document.documentElement;head.appendChild(style);}catch(e){tr('style error '+e);}}");
            AddMineJsLine(sb, "function findMenuCode(key,label){var pools=[];try{if(typeof mapbt!='undefined'&&mapbt)pools[pools.length]=mapbt;}catch(e){}try{if(typeof bavail!='undefined'&&bavail)pools[pools.length]=bavail;}catch(e){}try{if(typeof buttons!='undefined'&&buttons)pools[pools.length]=buttons;}catch(e){}for(var p=0;p<pools.length;p++){var a=pools[p];for(var i=0;i<a.length;i++){try{if(a[i]&&(String(a[i][0]||'')==key||String(a[i][1]||'')==label))return String(a[i][2]||'');}catch(e){}}}return '';}");
            AddMineJsLine(sb, "function addMineMenuButton(place,id,text,key,go,extra){var code=findMenuCode(key,text);var btn=document.getElementById(id);if(!code)return;if(!btn){btn=document.createElement('input');btn.type='button';btn.className='fr_but anc-mine-modern-btn';btn.id=id;btn.value=text;place.appendChild(document.createTextNode(' '));place.appendChild(btn);}btn.disabled=false;btn.className='fr_but anc-mine-modern-btn';btn.onclick=function(){try{var link='main.php?get_id=56&act=10&go='+go+'&vcode='+code+(extra||'');tr('manual menu open '+go+' during timer='+(routeWait()>0));window.location=link;}catch(e){tr('menu button error '+e);}return false;};}");
            AddMineJsLine(sb, "function addMineFloorExitButton(place){var btn=document.getElementById('ancMineFloorExitBtn');if(!btn){btn=document.createElement('input');btn.type='button';btn.className='fr_but anc-mine-modern-btn';btn.id='ancMineFloorExitBtn';btn.value='Пройти этаж';place.appendChild(document.createTextNode(' '));place.appendChild(btn);}var active=hasFloorExit();btn.disabled=!active;btn.className='fr_but anc-mine-modern-btn';btn.title=active?'Построить маршрут к переходу на следующий этаж':'Для этой шахты/этажа переход не настроен';btn.onclick=function(){if(btn.disabled)return false;return startFloorExit();};}");
            AddMineJsLine(sb, "function ensureMineMenuButtons(){var place=document.getElementById('ButtonPlace');if(!place)return;addMineMenuButton(place,'ancMineInfBtn','Ваш персонаж','inf','inf','');addMineMenuButton(place,'ancMineInvBtn','Инвентарь','inv','inv','');addMineFloorExitButton(place);}");
            AddMineJsLine(sb, "function ensureCenterButton(){var place=document.getElementById('ButtonPlace');if(!place)return;ensureMineMenuButtons();if(document.getElementById('ancMineCenterBtn'))return;var btn=document.createElement('input');btn.type='button';btn.className='fr_but';btn.id='ancMineCenterBtn';btn.value='Где я?';btn.onclick=function(){try{window.__ancMineScrollToElement();}catch(e){tr('center error '+e);}};place.appendChild(document.createTextNode(' '));place.appendChild(btn);}");
            AddMineJsLine(sb, "function buildCell(x,y){var size=cellSizeValue();var td=document.createElement('TD');td.style.width=size+'px';td.style.height=size+'px';td.style.position='relative';td.style.cursor='pointer';td.style.overflow='hidden';td.style.padding='0px';td.style.verticalAlign='top';td.style.backgroundColor='#101010';var img=resolveImg(bridgeImg(x,y));if(img)td.style.backgroundImage='url('+img+')';td.style.backgroundPosition='center center';td.style.backgroundRepeat='no-repeat';td.style.backgroundSize='cover';td.onclick=function(e){return clickCell(x,y,e);};td.ontouchend=function(e){try{if(now()<((window.__ancMineSuppressClickUntil)||0))return false;if(window.moved)return false;if(e&&e.preventDefault)e.preventDefault();var handled=clickCell(x,y,e);window.__ancMineSuppressClickUntil=now()+350;return handled;}catch(ex){tr('mine touch error '+ex);}return false;};var html=stripOnclick(bridgeHtml(x,y));td.innerHTML=cellContent(html||fallbackCell(x,y),size);return td;}");
            AddMineJsLine(sb, "function renderMine(){try{if(!isTunnel())return false;var content=document.getElementById('content');if(!content)return false;ensureMineStyles();syncMinePosition('render');ensureCenterButton();var serverMain=detachServerMineDom();content.innerHTML='';content.align='center';ensureServerMineDom(content,serverMain);var text=document.createElement('DIV');text.id='ancMineText';text.style.cssText='width:210px;position:absolute;margin-top:50px;margin-left:50%;left:-105px;top:0;z-index:1;font-family:Verdana;font-size:14px;color:white;font-weight:bold;text-shadow:black 1px 1px 0,black -1px -1px 0,black -1px 1px 0,black 1px -1px 0;';content.appendChild(text);var wrap=document.createElement('DIV');wrap.id='anc_main_tunnels';wrap.setAttribute('data-anc-scalable-mine','1');var h=document.documentElement.clientHeight||window.innerHeight||700;wrap.style.cssText='width:98%;height:'+Math.max(480,h-85)+'px;overflow:hidden;position:relative;margin:auto;';content.appendChild(wrap);window.__ancMineVisibleTunnels=wrap;var table=document.createElement('TABLE');var size=cellSizeValue();table.style.width=(21*size)+'px';table.style.position='absolute';table.style.left='0px';table.style.top='0px';table.style.transformOrigin='0 0';table.border=0;table.cellPadding=0;table.cellSpacing=0;wrap.appendChild(table);var tb=document.createElement('TBODY');table.appendChild(tb);for(var r=0;r<=20;r++){var trEl=document.createElement('TR');for(var c=0;c<=20;c++)trEl.appendChild(buildCell(c,r));tb.appendChild(trEl);}if(window.__ancMineDragDrop&&window.__ancMineDragDrop.init)window.__ancMineDragDrop.init(table);window.__ancMineScrollToElement();updateMoveText();tr('scalable mine rendered pos='+curX()+'/'+curY());return true;}catch(e){tr('render error '+e);return false;}}");
            AddMineJsLine(sb, "window.__ancMineScrollToElement=function(){var container=document.getElementById('anc_main_tunnels');if(!container||!container.firstChild)return;var table=container.firstChild;var spans=container.getElementsByTagName('SPAN');for(var i=0;i<spans.length;i++)spans[i].style.fontSize='10px';table.style.transform='scale(1)';if(window.__ancMineDragDrop)window.__ancMineDragDrop.scale=1;var size=cellSizeValue();var width=document.documentElement.clientWidth||window.innerWidth||760;var height=document.documentElement.clientHeight||window.innerHeight||600;table.style.left=(Math.round(width*0.49)-size*curX()-size/2)+'px';table.style.top=((height-85)/2-size*curY()-size/2)+'px';updateMoveText();};");
            AddMineJsLine(sb, "function stopEvent(e){try{if(e&&e.preventDefault)e.preventDefault();if(e)e.returnValue=false;}catch(x){}return false;}");
            AddMineJsLine(sb, "window.__ancMineDragDrop={init:function(container){this.moveState=false;this.x0=0;this.y0=0;this.elmX0=0;this.elmY0=0;this.container=container;this.scale=1;this.pinchStart=0;this.startScale=1;var self=this;container.onmousedown=function(e){return self.initMove(e||window.event);};document.onmouseup=function(){self.moveState=false;};document.onmousemove=function(e){return self.handlerMove(e||window.event);};container.onwheel=function(e){e=e||window.event;self.handleWheel(e.deltaY<0?1:-1);return stopEvent(e);};container.onmousewheel=function(e){e=e||window.event;self.handleWheel((e.wheelDelta||0)>0?1:-1);return stopEvent(e);};container.ontouchstart=function(e){return self.initMove(e);};container.ontouchmove=function(e){return self.handlerMove(e);};container.ontouchend=function(){self.moveState=false;self.pinchStart=0;};},point:function(e){if(e&&e.touches&&e.touches.length>0)e=e.touches[0];if(!e)e=window.event;return{x:(e.pageX||e.clientX||0),y:(e.pageY||e.clientY||0)};},dist:function(t){if(!t||t.length<2)return 0;var dx=t[0].pageX-t[1].pageX;var dy=t[0].pageY-t[1].pageY;return Math.sqrt(dx*dx+dy*dy);},initMove:function(e){window.moved=false;window.__ancMineSuppressClickUntil=0;if(e&&e.touches&&e.touches.length>1){this.pinchStart=this.dist(e.touches);this.startScale=this.scale;window.__ancMineSuppressClickUntil=now()+250;return stopEvent(e);}var p=this.point(e);this.x0=p.x;this.y0=p.y;this.elmX0=parseInt(this.container.style.left,10)||0;this.elmY0=parseInt(this.container.style.top,10)||0;this.moveState=true;return stopEvent(e);},handlerMove:function(e){if(e&&e.touches&&e.touches.length>1){var d=this.dist(e.touches);if(this.pinchStart>0)this.setScale(this.startScale*(d/this.pinchStart));window.__ancMineSuppressClickUntil=now()+250;return stopEvent(e);}if(this.moveState){var p=this.point(e);var movedNow=Math.abs(p.x-this.x0)>4||Math.abs(p.y-this.y0)>4;if(movedNow){window.moved=true;window.__ancMineSuppressClickUntil=now()+250;}this.container.style.left=(this.elmX0+p.x-this.x0)+'px';this.container.style.top=(this.elmY0+p.y-this.y0)+'px';return stopEvent(e);}return true;},handleWheel:function(delta){this.setScale(this.scale+(delta>0?0.1:-0.1));},setScale:function(newVal){if(newVal>1)newVal=1;if(newVal<0.5)newVal=0.5;this.scale=newVal;if(this.container)this.container.style.transform='scale('+this.scale+')';var spans=this.container?this.container.getElementsByTagName('SPAN'):[];var nv=Math.round(10+(1-this.scale)*20);for(var i=0;i<spans.length;i++)spans[i].style.fontSize=nv+'px';}};");
            AddMineJsLine(sb, "function installScalableMine(){if(window.__ancScalableMineInstalled)return;if(typeof window.show_tunnels!='function')return;window.__ancScalableMineInstalled=true;window.__ancOriginalShowTunnels=window.show_tunnels;window.show_tunnels=function(){var r;try{r=window.__ancOriginalShowTunnels.apply(this,arguments);}catch(e){tr('original show_tunnels error '+e);}try{captureServerCellImages();renderMine();window.__ancTryMineDig('show_tunnels');window.__ancScheduleMineRouteStep('show_tunnels',350);}catch(e){tr('scalable show_tunnels error '+e);}return r;};tr('show_tunnels overridden');}");
            AddMineJsLine(sb, "function installHooks(){try{if(window.Timer&&typeof window.Timer.start=='function'&&!window.Timer.start.__ancWrapped){var ots=window.Timer.start;window.Timer.start=function(sec){reportTimer(sec,'Timer.start');return ots.apply(this,arguments);};window.Timer.start.__ancWrapped=true;tr('Timer.start wrapped');}if(typeof window.display_move=='function'&&!window.display_move.__ancWrapped){var odm=window.display_move;window.display_move=function(tunn,time,dir){var accepted=String((typeof dir!='undefined'&&dir!==null)?dir:(window.__ancMineLastDispatchedDir||''));var r=odm.apply(this,arguments);rememberAcceptedMove(accepted,'display_move');return r;};window.display_move.__ancWrapped=true;tr('display_move wrapped');}if(typeof window.finFunction=='function'&&!window.finFunction.__ancWrapped){var ofn=window.finFunction;window.finFunction=function(){var advanced=applyAcceptedMove('finFunction');var r;try{r=ofn.apply(this,arguments);}finally{resetMoveState('finFunction');if(advanced){try{renderMine();}catch(e){tr('render after advance error '+e);}}window.__ancScheduleMineRouteStep('move_finish',350);}return r;};window.finFunction.__ancWrapped=true;tr('finFunction wrapped');}}catch(e){tr('install hooks error '+e);}}");
            AddMineJsLine(sb, "function wrap(){try{installScalableMine();installHooks();if(typeof view_mine=='function'&&!view_mine.__ancWrapped){var ovm=view_mine;view_mine=function(){installScalableMine();installHooks();var r=ovm.apply(this,arguments);setTimeout(function(){try{installScalableMine();installHooks();if(isTunnel())renderMine();updateMoveText();window.__ancTryMineDig('view_mine');window.__ancScheduleMineRouteStep('view_mine',500);}catch(e){tr('view_mine after error '+e);}},250);return r;};view_mine.__ancWrapped=true;tr('view_mine wrapped');}}catch(e){tr('wrap error '+e);}}");
            AddMineJsLine(sb, "wrap();setTimeout(wrap,300);");
            AddMineJsLine(sb, "})();");
            return sb.ToString();
        }

        private static void AddMineJsLine(StringBuilder builder, string line)
        {
            builder.Append(line);
            builder.Append("\r\n");
        }
    }
}
